steps:
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        python app.py
images:
  - 'gcr.io/$PROJECT_ID/web-app-image'
