steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python app.py
images:
  - 'gcr.io/$PROJECT_ID/web-app-image'
