steps:
  # Step to install dependencies
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/serverless-image-processing/web-app-image', '.']

  # Step to push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/serverless-image-processing/web-app-image']

images:
  - 'gcr.io/serverless-image-processing/web-app-image'
